using System.Reflection;

// CommandAssistant Git@Sombody101

// Automatically generated by AssemblyInfo.tt on Thursday, August 24, 2023 11:26:18 AM

/*
 * 0-1 : Alpha
 * 2   : Beta
 * 3   : Full release
 */

[assembly: AssemblyVersion("2.08.24.1126")]
[assembly: AssemblyFileVersion("2.08.24.1126")]
[assembly: AssemblyTitle("CommandAssistant")]