using System.Reflection;

// CommandAssistant Git@Sombody101

// Automatically generated by AssemblyInfo.tt on Monday, August 28, 2023 09:54:43 AM

/*
 * 0-1 : Alpha
 * 2   : Beta
 * 3   : Full release
 */

[assembly: AssemblyVersion("2.08.28.0954")]
[assembly: AssemblyFileVersion("2.08.28.0954")]
[assembly: AssemblyTitle("CommandAssistant")]